ARG CI_DEP_IMG
FROM ${CI_DEP_IMG}

RUN \
    cd /opt/mxe && \
    make --jobs=$(nproc) JOBS=$(nproc) MXE_TARGETS='x86_64-w64-mingw32.shared' qt6-qttools qt6-qtimageformats && \
    exit 0

ENV PATH=/opt/mxe/usr/bin:/opt/mxe/usr/x86_64-w64-mingw32.shared/qt6/bin:${PATH}

RUN \
    set -eux && \
    echo $PATH && \
    ln -s /opt/mxe/usr/bin/x86_64-w64-mingw32.shared-cmake /usr/local/bin/cmake && \
    cmake --version && \
    qmake --version && \
    exit 0
